#### THIS FILE IS MANAGED BY AN AUTOMATED WORKFLOW ####

name: pre-commit

on:
  pull_request:
    branches:
      - main
      - master
      - "!repo-sync/**"
      - "!renovate/**"
      - "!update/pre-commit-hooks/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5 # tag=v4
      - uses: pre-commit/action@v3.0.0
